name: Redis CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'backend_redis/**'
 

jobs:
  build-and-deploy:
    name: Build and Deploy Docker Image
    runs-on: ubuntu-latest

    env:
      CLUSTER_NAME: main-ecs-cluster
      REDIS_SERVICE_NAME: redis
      AWS_REGION: us-east-1
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }} 

    steps:
     
      - name: Checkout code
        uses: actions/checkout@v3

     
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

     
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      
      - name: Build & Push Docker image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/repo/redis:${{ github.sha }} backend_redis -f backend_redis/Dockerfile
          docker push ${{ steps.login-ecr.outputs.registry }}/repo/redis:${{ github.sha }}

       
      - name: Download task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition redis-task-definition \
            --query taskDefinition \
            --output json > task-definition.json

       
      - name: Debug task definition
        run: |
          echo "Task definition content:"
          cat task-definition.json

        
      - name: Fill in new image ID in task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: redis
          image: ${{ steps.login-ecr.outputs.registry }}/repo/redis:${{ github.sha }}

      
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: redis
          cluster: main-ecs-cluster

      - name: Update ECS service
        run: |
          aws ecs update-service --cluster main-ecs-cluster --service redis --force-new-deployment --region ${{ env.AWS_REGION }}
